model_type: ci2v

denoising_step_list:
  - 1000
  - 750
  - 500
  - 250
warp_denoising_step: true
context_noise: 0

image_or_video_shape:
  - 1
  - 31
  - 48
  - 44
  - 80
independent_first_frame: true
num_frame_per_block: 3

ref_num_slots: 5
ref_resolution: 512

model_kwargs:
  model_name: checkpoints/ABot-World-0-5B-LF
  timestep_shift: 5.0
  local_attn_size: 21
  use_relative_rope: true
  downscale_factor_control_adapter: 16

text_encoder_kwargs:
  tokenizer_path: checkpoints/ABot-World-0-5B-LF/google/umt5-xxl/
  encoder_pth_path: checkpoints/ABot-World-0-5B-LF/models_t5_umt5-xxl-enc-bf16.pth

vae_kwargs:
  vae_type: Wan2.2_VAE
  pretrained_path: checkpoints/ABot-World-0-5B-LF/Wan2.2_VAE.pth
